'use strict';
/* Stages, WarioWare-style: each one has a "host" (a recoloured Claude), a themed pool of
   microgames, a speed curve and a boss at the end. Game ids come from REG (see js/games/).
   Every stage has its own boss with its own mechanic (no two stages share one); bosses live in js/games/bosses.js and js/bosses/. */
const STAGES = [
  { name: 'BUG HUNT', tag: 'Click it. Squash it.', col: '#D97757', bg: ['#B8E05A', '#a8d046'],
    pool: ['swat', 'whack', 'spot', 'count', 'dodge', 'slice'], n: 8, sp0: 1.0, boss: 'bug', bossHp: 10 },
  { name: 'KEYBOARD KINGDOM', tag: 'Fingers on the keys!', col: '#6EA8FE', bg: ['#FF8FD0', '#ff7cc6'],
    pool: ['type', 'copy', 'math', 'race', 'sort', 'maze'], n: 8, sp0: 1.1, boss: 'type', bossWord: 'REFACTOR' },
  { name: 'REFLEX RUSH', tag: 'Faster. Then faster.', col: '#7BD88F', bg: ['#6EC6FF', '#5fb8f5'],
    pool: ['jump', 'stop', 'reflex', 'flap', 'charge', 'dont'], n: 8, sp0: 1.2, boss: 'stomp' },
  { name: 'MOUSE MAYHEM', tag: 'Point, drag, scrub!', col: '#F28CB1', bg: ['#FFE9A8', '#ffe08c'],
    pool: ['steady', 'drag', 'scrub', 'crank', 'wires', 'mash'], n: 8, sp0: 1.3, boss: 'fan' },
  { name: 'BRAIN BREAK', tag: 'Think fast!', col: '#B49CFF', bg: ['#A0E7E5', '#8fdbd9'],
    pool: ['flip', 'shell', 'rps', 'balance', 'catch', 'pong'], n: 8, sp0: 1.4, boss: 'simon' },
  { name: 'MEGA MIX', tag: 'Everything. At once.', col: '#FFD23F', bg: ['#FF9AA2', '#ff8892'],
    pool: null /* every game */, n: 12, sp0: 1.5, boss: 'dodge', bossBalls: 5 },
  { name: 'WII WAGGLE', tag: 'Smooth moves, Claude!', col: '#4DB8FF', bg: ['#DDF3FF', '#c9ecff'],
    pool: ['wii_save', 'wii_zap', 'wii_draw', 'wii_sneak', 'wii_umbrella', 'wii_pop', 'wii_strike', 'wii_shave', 'wii_fan', 'wii_twirl', 'wii_roll', 'wii_close'], n: 8, sp0: 1.2, boss: 'conduct' },
  { name: 'CUBE PARTY', tag: 'Mega party game, mega fast!', col: '#9B6BD1', bg: ['#D9C7FF', '#cbb4ff'],
    pool: ['gc_sole', 'gc_rhino', 'gc_alley', 'gc_pinball', 'gc_batter', 'gc_snap', 'gc_trap', 'gc_douse', 'gc_putt', 'gc_park', 'gc_goalie', 'gc_nail'], n: 8, sp0: 1.3, boss: 'burger' },
  { name: 'TOUCH SCREEN', tag: 'Poke it. Draw it. Cut it.', col: '#FF8FA3', bg: ['#FFD6E0', '#ffc6d4'],
    pool: ['ds_ramp', 'ds_creep', 'ds_fuse', 'ds_loop', 'ds_cage', 'ds_fan', 'ds_pose', 'ds_sink', 'ds_scratch', 'ds_faces', 'ds_tune', 'ds_strip'], n: 8, sp0: 1.3, boss: 'galaxy' },
  { name: 'GET TOGETHER', tag: 'Stay still. Pick. Run. Fry.', col: '#FF6B4D', bg: ['#FFE0B8', '#ffd49c'],
    pool: ['sw_freeze', 'sw_pick', 'sw_run', 'sw_wanted', 'sw_fry', 'sw_fill', 'sw_limbo', 'sw_steer', 'sw_sleep', 'sw_stars', 'sw_draw', 'sw_protect'], n: 8, sp0: 1.4, boss: 'samurai' },
  { name: '3D DIMENSION', tag: 'Now with depth!', col: '#3DDC97', bg: ['#BFEFFF', '#a9e4fb'],
    pool: ['td_stack', 'td_bowl', 'td_dive', 'td_hoop', 'td_tunnel', 'td_mole', 'td_roll', 'td_basket', 'td_cube', 'td_lanes', 'td_crane', 'td_hop'], n: 8, sp0: 1.3, boss: 'road' },
  { name: 'MEGA MICROGAME$', tag: 'Old-school. Four colours. Go!', col: '#8BAC0F', bg: ['#9BBC0F', '#8BAC0F'],
    pool: ['mm_rope', 'mm_stamp', 'mm_toast', 'mm_shoot', 'mm_pump', 'mm_phone', 'mm_sumo', 'mm_wash'], n: 8, sp0: 1.2, boss: 'dungeon' },
  { name: 'TWISTED!', tag: 'Tilt it. Spin it. Steer it!', col: '#FF9F1C', bg: ['#FFE5B4', '#ffd9a0'],
    pool: ['tw_tilt', 'tw_spin', 'tw_pour', 'tw_dial', 'tw_slide', 'tw_wheel', 'tw_coins', 'tw_skate'], n: 8, sp0: 1.3, boss: 'crank' },
  { name: 'MOVE IT!', tag: 'Strike a pose. Hit the beat!', col: '#E040FB', bg: ['#F3C6FF', '#ecb2fb'],
    pool: ['mv_pose', 'mv_mirror', 'mv_beat', 'mv_swim', 'mv_punch', 'mv_wave', 'mv_clap', 'mv_balance'], n: 8, sp0: 1.3, boss: 'rhythm', intro: 'mv' },
  { name: 'BRAINY BUNCH', tag: 'Spot it. Weigh it. Match it!', col: '#4D8DFF', bg: ['#DDF0FF', '#c9e6ff'],
    pool: ['bb_scale', 'bb_behind', 'bb_focus', 'bb_mutation', 'bb_profiler', 'bb_numbers', 'bb_statues', 'bb_buttons'], n: 8, sp0: 1.2, boss: 'tiles' },
  { name: 'CRITTER CLUB', tag: 'Herd it. Catch it. Scare it!', col: '#6CC24A', bg: ['#E6F7C8', '#d8f0b0'],
    pool: ['cc_hare', 'cc_pig', 'cc_cat', 'cc_dog', 'cc_worm', 'cc_claw', 'cc_frog', 'cc_hen'], n: 8, sp0: 1.2, boss: 'sort' },
  { name: 'SPORTS DAY', tag: 'Wind up. Release. Score!', col: '#FF7A3D', bg: ['#FFE3C9', '#ffd5b0'],
    pool: ['sd_hammer', 'sd_ski', 'sd_bowl', 'sd_curl', 'sd_hoops', 'sd_volley', 'sd_rope', 'sd_star'], n: 8, sp0: 1.3, boss: 'batter' },
  { name: 'LINES & LIGHT', tag: 'Steady hands. Bright ideas!', col: '#F2B600', bg: ['#FFF3C2', '#ffeaa0'],
    pool: ['ln_sew', 'ln_road', 'ln_cable', 'ln_sign', 'ln_magna', 'ln_green', 'ln_plates', 'ln_edge'], n: 8, sp0: 1.3, boss: 'laser' },
  { name: 'POWER OUT!', tag: 'The light is gone. Again.', col: '#FFCC00', bg: ['#1F3FA8', '#142B7A'],
    pool: ['ap_switch', 'ap_fridge', 'ap_mosquito', 'ap_battery', 'ap_arepa', 'ap_grita'], n: 8, sp0: 1.2, boss: 'blackout', intro: 'ap' }
];
