'use strict';
// Capture the app's actual registration list without running game constructors or WebGL.
// node scripts/party-catalog.js [--check]
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const root = path.resolve(__dirname, '..');
function registrations() {
  const captured = [], sandbox = { W: 800, H: 600, VW: 800, OX: 0, Math, console, AP: {},
    reg: (id, fn) => captured.push({ id, fn }), reg3: (id, fn) => captured.push({ id, fn }) };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  const files = [...html.matchAll(/<script src="(js\/games\/[^"?]+)(?:\?[^" ]*)?"/g)].map(m => m[1]);
  for (const file of files) {
    if (file.endsWith('/td_core.js') || file.endsWith('/du1.js')) continue; // keep the original reg3 callback, not the WebGL fallback
    if (file === 'js/games/crew.js' || file.startsWith('js/games/duo/')) continue;                          // DUO-only games (they need du1.js's kit): never in the shared catalog
    vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), sandbox, { filename: file });
  }
  return captured;
}
function catalog() {
  const result = {};
  for (const { id, fn } of registrations()) {
    if (id.startsWith('du_')) continue; // paired-role games have their own DUO mode
    const source = fn.toString(), match = source.match(/\bdur\s*:\s*([^,}\n]+)/);
    if (!match) throw new Error('Missing duration for ' + id);
    let expression = match[1];
    if (/^[A-Z_]+$/.test(expression.trim())) {
      const constant = source.match(new RegExp('\\b' + expression.trim() + '\\s*=\\s*([0-9.]+)'));
      if (!constant) throw new Error('Unknown duration constant for ' + id);
      expression = constant[1];
    }
    expression = expression.trim();
    // Reject new expression forms instead of silently mistaking a coefficient for a duration.
    if (!/^(?:\d+(?:\.\d+)?|[a-zA-Z_$][\w$]*\s*\?\s*\d+(?:\.\d+)?\s*:\s*\d+(?:\.\d+)?)$/.test(expression))
      throw new Error('Unsupported duration expression for ' + id + ': ' + expression);
    const numbers = expression.match(/\d+(?:\.\d+)?/g);
    if (!numbers) throw new Error('Unknown duration for ' + id);
    if (result[id]) throw new Error('Duplicate id: ' + id);
    result[id] = { dur: Math.max(...numbers.map(Number)), pts: id === 'pt_mash' || id === 'pt_sync' || id === 'pt_grab' };
  }
  return result;
}
function render() { return "// Generated by scripts/party-catalog.js from the app's registered microgames.\nmodule.exports = " + JSON.stringify(catalog(), null, 2) + ';\n'; }
if (require.main === module) {
  const file = path.join(root, 'pocketbase/pb_hooks/party_catalog.js'), output = render();
  if (process.argv.includes('--check')) { if (fs.readFileSync(file, 'utf8') !== output) throw new Error('Party catalog is stale; run node scripts/party-catalog.js'); }
  else fs.writeFileSync(file, output);
  console.log(Object.keys(catalog()).length + ' microgames in party catalog');
}
module.exports = { catalog, render, registrations };
