// Generated by scripts/party-catalog.js from the app's registered microgames.
module.exports = {
  "swat": {
    "dur": 5,
    "pts": false
  },
  "jump": {
    "dur": 4.4,
    "pts": false
  },
  "type": {
    "dur": 5.5,
    "pts": false
  },
  "spot": {
    "dur": 4.5,
    "pts": false
  },
  "mash": {
    "dur": 4.5,
    "pts": false
  },
  "catch": {
    "dur": 5.2,
    "pts": false
  },
  "stop": {
    "dur": 5,
    "pts": false
  },
  "dont": {
    "dur": 4,
    "pts": false
  },
  "count": {
    "dur": 5,
    "pts": false
  },
  "slice": {
    "dur": 5,
    "pts": false
  },
  "copy": {
    "dur": 5,
    "pts": false
  },
  "steady": {
    "dur": 6,
    "pts": false
  },
  "whack": {
    "dur": 5,
    "pts": false
  },
  "drag": {
    "dur": 5.5,
    "pts": false
  },
  "race": {
    "dur": 5,
    "pts": false
  },
  "reflex": {
    "dur": 4,
    "pts": false
  },
  "rps": {
    "dur": 4.5,
    "pts": false
  },
  "math": {
    "dur": 5,
    "pts": false
  },
  "sort": {
    "dur": 5,
    "pts": false
  },
  "shell": {
    "dur": 6.5,
    "pts": false
  },
  "scrub": {
    "dur": 5.5,
    "pts": false
  },
  "dodge": {
    "dur": 5,
    "pts": false
  },
  "balance": {
    "dur": 5,
    "pts": false
  },
  "flip": {
    "dur": 6.5,
    "pts": false
  },
  "charge": {
    "dur": 5,
    "pts": false
  },
  "flap": {
    "dur": 4.5,
    "pts": false
  },
  "pong": {
    "dur": 4.8,
    "pts": false
  },
  "crank": {
    "dur": 5,
    "pts": false
  },
  "maze": {
    "dur": 7,
    "pts": false
  },
  "wires": {
    "dur": 5.5,
    "pts": false
  },
  "wii_save": {
    "dur": 6.2,
    "pts": false
  },
  "wii_zap": {
    "dur": 6,
    "pts": false
  },
  "wii_draw": {
    "dur": 4.6,
    "pts": false
  },
  "wii_sneak": {
    "dur": 6.2,
    "pts": false
  },
  "wii_umbrella": {
    "dur": 4.8,
    "pts": false
  },
  "wii_pop": {
    "dur": 5.8,
    "pts": false
  },
  "wii_strike": {
    "dur": 5,
    "pts": false
  },
  "wii_shave": {
    "dur": 6.5,
    "pts": false
  },
  "wii_fan": {
    "dur": 5.2,
    "pts": false
  },
  "wii_twirl": {
    "dur": 6.2,
    "pts": false
  },
  "wii_roll": {
    "dur": 5,
    "pts": false
  },
  "wii_close": {
    "dur": 5,
    "pts": false
  },
  "gc_sole": {
    "dur": 5,
    "pts": false
  },
  "gc_rhino": {
    "dur": 5.8,
    "pts": false
  },
  "gc_alley": {
    "dur": 5.6,
    "pts": false
  },
  "gc_pinball": {
    "dur": 5,
    "pts": false
  },
  "gc_batter": {
    "dur": 4.2,
    "pts": false
  },
  "gc_snap": {
    "dur": 5,
    "pts": false
  },
  "gc_trap": {
    "dur": 5.2,
    "pts": false
  },
  "gc_douse": {
    "dur": 6.2,
    "pts": false
  },
  "gc_putt": {
    "dur": 6.5,
    "pts": false
  },
  "gc_park": {
    "dur": 6,
    "pts": false
  },
  "gc_goalie": {
    "dur": 5.4,
    "pts": false
  },
  "gc_nail": {
    "dur": 6,
    "pts": false
  },
  "ds_ramp": {
    "dur": 4.8,
    "pts": false
  },
  "ds_creep": {
    "dur": 5.5,
    "pts": false
  },
  "ds_fuse": {
    "dur": 4.6,
    "pts": false
  },
  "ds_loop": {
    "dur": 5.8,
    "pts": false
  },
  "ds_cage": {
    "dur": 4.6,
    "pts": false
  },
  "ds_fan": {
    "dur": 4.8,
    "pts": false
  },
  "ds_pose": {
    "dur": 5.8,
    "pts": false
  },
  "ds_sink": {
    "dur": 5.2,
    "pts": false
  },
  "ds_scratch": {
    "dur": 5.8,
    "pts": false
  },
  "ds_faces": {
    "dur": 5.5,
    "pts": false
  },
  "ds_tune": {
    "dur": 5.4,
    "pts": false
  },
  "ds_strip": {
    "dur": 4.8,
    "pts": false
  },
  "sw_freeze": {
    "dur": 4,
    "pts": false
  },
  "sw_pick": {
    "dur": 5,
    "pts": false
  },
  "sw_run": {
    "dur": 5,
    "pts": false
  },
  "sw_wanted": {
    "dur": 5,
    "pts": false
  },
  "sw_fry": {
    "dur": 5,
    "pts": false
  },
  "sw_fill": {
    "dur": 5,
    "pts": false
  },
  "sw_limbo": {
    "dur": 5,
    "pts": false
  },
  "sw_steer": {
    "dur": 4.5,
    "pts": false
  },
  "sw_sleep": {
    "dur": 5,
    "pts": false
  },
  "sw_stars": {
    "dur": 7,
    "pts": false
  },
  "sw_draw": {
    "dur": 5,
    "pts": false
  },
  "sw_protect": {
    "dur": 5,
    "pts": false
  },
  "td_stack": {
    "dur": 7,
    "pts": false
  },
  "td_bowl": {
    "dur": 7,
    "pts": false
  },
  "td_dive": {
    "dur": 7,
    "pts": false
  },
  "td_hoop": {
    "dur": 7,
    "pts": false
  },
  "td_tunnel": {
    "dur": 6,
    "pts": false
  },
  "td_mole": {
    "dur": 7,
    "pts": false
  },
  "td_roll": {
    "dur": 8,
    "pts": false
  },
  "td_basket": {
    "dur": 8,
    "pts": false
  },
  "td_cube": {
    "dur": 7,
    "pts": false
  },
  "td_lanes": {
    "dur": 7,
    "pts": false
  },
  "td_crane": {
    "dur": 9,
    "pts": false
  },
  "td_hop": {
    "dur": 8,
    "pts": false
  },
  "mm_rope": {
    "dur": 5,
    "pts": false
  },
  "mm_stamp": {
    "dur": 5,
    "pts": false
  },
  "mm_toast": {
    "dur": 5,
    "pts": false
  },
  "mm_shoot": {
    "dur": 5,
    "pts": false
  },
  "mm_pump": {
    "dur": 5,
    "pts": false
  },
  "mm_phone": {
    "dur": 6.5,
    "pts": false
  },
  "mm_sumo": {
    "dur": 5,
    "pts": false
  },
  "mm_wash": {
    "dur": 5.5,
    "pts": false
  },
  "tw_tilt": {
    "dur": 5,
    "pts": false
  },
  "tw_spin": {
    "dur": 4.5,
    "pts": false
  },
  "tw_pour": {
    "dur": 5,
    "pts": false
  },
  "tw_dial": {
    "dur": 5,
    "pts": false
  },
  "tw_slide": {
    "dur": 5,
    "pts": false
  },
  "tw_wheel": {
    "dur": 5,
    "pts": false
  },
  "tw_coins": {
    "dur": 6,
    "pts": false
  },
  "tw_skate": {
    "dur": 5,
    "pts": false
  },
  "mv_pose": {
    "dur": 4.5,
    "pts": false
  },
  "mv_mirror": {
    "dur": 6,
    "pts": false
  },
  "mv_beat": {
    "dur": 5,
    "pts": false
  },
  "mv_swim": {
    "dur": 5,
    "pts": false
  },
  "mv_punch": {
    "dur": 5.6,
    "pts": false
  },
  "mv_wave": {
    "dur": 5,
    "pts": false
  },
  "mv_clap": {
    "dur": 4.6,
    "pts": false
  },
  "mv_balance": {
    "dur": 5,
    "pts": false
  },
  "pt_mash": {
    "dur": 5,
    "pts": true
  },
  "pt_sync": {
    "dur": 5,
    "pts": true
  },
  "pt_memo": {
    "dur": 8,
    "pts": false
  },
  "pt_grab": {
    "dur": 7,
    "pts": true
  },
  "bb_scale": {
    "dur": 5.4,
    "pts": false
  },
  "bb_behind": {
    "dur": 5.8,
    "pts": false
  },
  "bb_focus": {
    "dur": 5.6,
    "pts": false
  },
  "bb_mutation": {
    "dur": 5.8,
    "pts": false
  },
  "bb_profiler": {
    "dur": 5.8,
    "pts": false
  },
  "bb_numbers": {
    "dur": 5.8,
    "pts": false
  },
  "bb_statues": {
    "dur": 5.8,
    "pts": false
  },
  "bb_buttons": {
    "dur": 5.6,
    "pts": false
  },
  "cc_hare": {
    "dur": 5.6,
    "pts": false
  },
  "cc_pig": {
    "dur": 6,
    "pts": false
  },
  "cc_cat": {
    "dur": 5.6,
    "pts": false
  },
  "cc_dog": {
    "dur": 5.6,
    "pts": false
  },
  "cc_worm": {
    "dur": 6,
    "pts": false
  },
  "cc_claw": {
    "dur": 6,
    "pts": false
  },
  "cc_frog": {
    "dur": 6,
    "pts": false
  },
  "cc_hen": {
    "dur": 6,
    "pts": false
  },
  "sd_hammer": {
    "dur": 5.6,
    "pts": false
  },
  "sd_ski": {
    "dur": 5.4,
    "pts": false
  },
  "sd_bowl": {
    "dur": 5.8,
    "pts": false
  },
  "sd_curl": {
    "dur": 5.6,
    "pts": false
  },
  "sd_hoops": {
    "dur": 5.6,
    "pts": false
  },
  "sd_volley": {
    "dur": 5.4,
    "pts": false
  },
  "sd_rope": {
    "dur": 5.8,
    "pts": false
  },
  "sd_star": {
    "dur": 5.8,
    "pts": false
  },
  "ln_sew": {
    "dur": 5.8,
    "pts": false
  },
  "ln_road": {
    "dur": 5.8,
    "pts": false
  },
  "ln_cable": {
    "dur": 5.8,
    "pts": false
  },
  "ln_sign": {
    "dur": 5.6,
    "pts": false
  },
  "ln_magna": {
    "dur": 5.6,
    "pts": false
  },
  "ln_green": {
    "dur": 5.8,
    "pts": false
  },
  "ln_plates": {
    "dur": 5.8,
    "pts": false
  },
  "ln_edge": {
    "dur": 5.9,
    "pts": false
  },
  "ap_switch": {
    "dur": 5,
    "pts": false
  },
  "ap_fridge": {
    "dur": 5,
    "pts": false
  },
  "ap_mosquito": {
    "dur": 5,
    "pts": false
  },
  "ap_battery": {
    "dur": 5,
    "pts": false
  },
  "ap_arepa": {
    "dur": 5,
    "pts": false
  },
  "ap_grita": {
    "dur": 5,
    "pts": false
  }
};
